#!/bin/bash

set -xe

name=gr-liquidDSP

prefix=/usr/local/encap/${name}-00

cd "$(dirname ${BASH_SOURCE[0]})"

rm -rf ${prefix}
rm -rf BUILD/
rm -f test2.py

mkdir -p BUILD


cd BUILD
cmake .. -G"Unix Makefiles"\
 -DPYTHON_EXECUTABLE:FILEPATH=/usr/local/bin/python3\
 -DCMAKE_INSTALL_PREFIX:PATH="${prefix}"\
 -DCMAKE_INSTALL_RPATH:PATH="${prefix}/lib:/usr/local/lib"

make VERBOSE=1
make install

set +x

cat << EOF

   SUCCESSFULLY installed $name in $prefix

EOF


if [ "$(whoami)" = "lance" ] ; then
    sudo encap
fi

cd -

exec Gnuradio-companion test.grc
